import { object, string, number, date } from 'yup'


export let createSmegaMinorSchema = object({
  formId: string().required(),
  recRef: string().required(),
  firstName: string().required(),
  lastName: string().required(),
  birthCountry: string().required(),
  birthDate: date().required(),
  idNumber: string().required(),
  idType: string().required(),
  gender: string().required(),
  msisdn: number().required(),
  guardianFirstName: string().required(),
  guardianLastName: string().required(),
  guardianOccupation: string().required(),
  guardianDOB: date().required(),
  guardianIDNumber: number().required(),
  guardianIDType: string().required(),
  guardianAddress: string(),
  guardianWard: string(),
  guardianDistrict: string(),
  guardianRelationship: string(),
  guardianContact: string().required(),
  agentName: '',
  location: '',
  agentOutlet: '',
  signature: '',
  date: '',
  createdOn: '',
})

export const createSmegaCustomerSchema = object({
  operation_type: number().required(),
  firstnames: string().required(),
  lastname: string().required(),
  date_of_birth: date().required(),
  country_of_birth: string().required(),
  gender: string().required(),
  id_type: number().required(),
  id_number: string().required(),
  id_valid_until: date().required(),
  occupation: string().nullable(),
  profession: string().nullable(),
  physical_address: string().nullable(),
  postal_address: string().nullable(),
  btc_number: string().required().length(8),
  other_contact: string().nullable(),
  email: string().email().optional().nullable(),
  next_of_kin: string().optional().nullable(),
  nok_relationship: string().optional().nullable(),
  nok_contact: string().optional().length(8).nullable(),
  created_on: date().required(),
  agent_name: string().optional().nullable(),
  agent_email: string().email().nullable(),
  serviced_on: date().optional().nullable(),
})
